spring:
  application:
    name: tools-utils
  mail:
    host: smtp.qq.com
    username: 1440651649@qq.com
    password: ENC(r5c/qpcCtAH7ADfHmyI/7GAQ4251dQbjLLal/7IedII=)
    port: 465
    protocol: smtp
    jndiName: 亲爱的
    properties:
      mail:
        smtp:
          socketFactoryClass: javax.net.ssl.SSLSocketFactory
          ssl:
            enable: true
server:
  port: 4040

jasypt:
  encryptor:
    password: ${jasypt.password}

file:
  upload:
    path: /home/tools/upload
  url: http://tools.fengzhengx.cn/file/down
